# Generated by Django 4.2.13 on 2024-07-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('refresh_token', models.CharField(max_length=100)),
                ('person_id', models.CharField(max_length=100)),
            ],
        ),
    ]
