# Generated by Django 4.2.13 on 2025-07-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_scheduleoverride_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiSummaryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('generated', models.DateTimeField()),
                ('expires', models.DateTimeField()),
                ('person_id', models.CharField(max_length=100)),
                ('context', models.TextField()),
            ],
        ),
    ]
