# Generated by Django 4.2.13 on 2025-08-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_betauser'),
    ]

    operations = [
        migrations.AddField(
            model_name='betauser',
            name='ai',
            field=models.BooleanField(default=False),
        ),
    ]
