# Generated by Django 4.2.13 on 2025-08-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_betauser_ai'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleoverride',
            name='school',
            field=models.CharField(choices=[('MS', 'Middle School'), ('HS', 'Upper School')], default='MS', max_length=5),
        ),
        migrations.AlterField(
            model_name='scheduleoverride',
            name='schedule',
            field=models.CharField(choices=[('all', 'Normal MTF'), ('wed', 'Normal Wednesday'), ('thurs', 'Normal Thursday'), ('early', 'Early Dismissal'), ('amass', 'AM Assembly'), ('pmass', 'PM Assembly'), ('A', 'A Schedule'), ('B', 'B Schedule'), ('C', 'C Schedule'), ('D', 'D Schedule'), ('E', 'E Schedule'), ('F', 'F Schedule'), ('G', 'G Schedule'), ('H', 'H Schedule'), ('special', 'Other')], max_length=20),
        ),
    ]
