# Generated by Django 4.2.13 on 2026-01-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_scheduleoverride_school_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountdownEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('all_grades', models.BooleanField(default=False)),
                ('grade', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
